language: node_js
node_js:
  - "0.10"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg

notifications:
  irc:
    channels:
      - "irc.mozilla.org#janus"
    on_success: change
    on_failure: always
