# Logging settings.
logging:
  # The minimum logging level for console messages
  # (via Winston, https://github.com/flatiron/winston).
  level: debug
  # Whether or not to colorize console logging.
  colorize: true

# Node Cluster options.
cluster:
  enabled: false
  workers:
    # When true (the default), the number of workers
    # is determined automatically based on number
    # of CPUs on the machine.
    auto: true

    # When 'auto' is false, this number is used to
    # determine the number of workers.
    count: 8

# Proxy server settings.
proxy:
  # Proxy listen port.
  port: 55055

  # SSL key path.
  sslKeyPath: ./keys/key.pem

  # SSL certificate path.
  sslCertPath: ./keys/crt.pem

  # Whether or not the proxy will follow redirects
  # itself or pass them back to the client.
  followRedirects: false


# PAC (proxy auto config) server settings.
pac:
  # PAC server listen port.
  port: 55155
  # Whether or not to tunnel SSL traffic.
  tunnelSsl: false


# Plugin settings below.
#
# If a plugin has no config, the default looks like this:
#
# pluginName:
#   enabled: false
#   optional: false
#
# If 'enabled' is true, the plugin is loaded and used
# by default. If false, it is not. If 'optional' is
# true, it means the plugin can be enabled and disabled
# by request-specific headers. The initial state is
# still determined by the 'enabled' value.

# DOM plugin, provides its own plugin system for
# operating on a parsed HTML DOM.
dom:
  enabled: true

# ingress plugin, reads data from the forwarded response.
ingress:
  enabled: true

# egress plugin delivers the end result to the client.
egress:
  enabled: true

# gunzip plugin unzips gzip-formatted content, usually
# because we need to parse it for the DOM plugin.
gunzip:
  enabled: true

# Cache settings.
cache:
  enabled: true

  # Supported cache types are:
  # + basic (in-memory JS)
  # + redis (requires Redis database)
  type: basic

  # Settings for non-basic database server.
  database:
    host: localhost
    port: 55255

  # Expiration time settings for cache items in seconds.
  expire:
    default: 30
    max: 604800

  # Cache items management.
  items:
    enabled: false
    limit: 5000000

  # Cache memory usage settings in MB.
  memory:
    enabled: true
    limit: 2000

# Image compression settings.
imgcompression:
  enabled: true

# Adblock settings.
adblock:
  enabled: false
  optional: true
  listUrl: 'http://pgl.yoyo.org/adservers/serverlist.php?&mimetype=plaintext'

# XZ compression settings.
xz:
  enabled: true
  # Anything higher requires a lot of memory to decode (> 32MB).
  level: 8

# Gzip compression settings.
gzip:
  enabled: true
  # Compression level.
  level: 9

# GIF to video transcoding settings.
gif2video:
  enabled: false
  optional: true

# Metrics reporting settings.
metrics:
  enabled: true
  # Update interval settings in seconds.
  interval:
    # Update interval for general system stats reporting.
    systemUpdate: 60
  # Settings for the StatsD backend (see config/statsd.js).
  # Only the host and prefix settings are special, as they are used for the
  # client-only configuration.
  statsd:
    host: localhost
    port: 55355
    prefix: janus
    # Spawn an instance of StatsD to connect to if enabled, otherwise just
    # use the settings to connect to an existing service.
    spawn: true

    # The following settings only have effect if spawning is enabled.

    flushInterval: 60000
    # Supported backends are (use ./backends/ prefix): 
    # + graphite
    # + console
    # + debug (cleaner console output)
    backends: [./backends/debug]
    graphiteHost: localhost
    graphitePort: 55455
    console:
      prettyprint: true

# Test settings
test:
  logLevel: error

  # test/tests/performance.js settings
  performance:
    enabled: false

  phantom:
    host: '127.0.0.1'
    port: 3000

  proxy:
    host: '127.0.0.1'
    port: 44044

  localServer:
    port: 8080
