
logging:
  # The minimum logging level for console messages
  # (via Winston, https://github.com/flatiron/winston)
  level: debug

# Node Cluster options
cluster:
  enabled: false
  workers:
    # When true (the default), the number of workers
    # is determined automatically based on number
    # of CPUs on the machine.
    auto: true

    # When 'auto' is false, this number is used to
    # determine the number of workers.
    count: 8

# Gonzales server settings.
proxy:
  # Gonzales listen port.
  port: 55055

  # SSL key path.
  sslKeyPath: ./keys/key.pem

  # SSL certificate path.
  sslCertPath: ./keys/crt.pem

  # Whether or not the proxy will follow redirects
  # itself or pass them back to the client
  followRedirects: false


# PAC (proxy auto config) server settings.
pac:
  # PAC server listen port.
  port: 55155


# Plugin settings below.

# Cache settings.
cache:
  enabled: true

  # Supported cache types are:
  # - basic (in-memory JS)
  # - redis (requires Redis database)
  type: basic

  # Settings for non-basic database server.
  database:
    host: localhost
    port: 55255

  # Expiration time settings for cache items in seconds.
  expire:
    default: 30
    max: 604800

  # Cache items management.
  items:
    enabled: false
    limit: 5000000

  # Cache memory usage settings in MB.
  memory:
    enabled: true
    limit: 2000

# Image compression settings.
imgcompression:
  enabled: true

# Adblock settings.
adblock:
  enabled: false

# Gzip compression settings.
gzip:
  # Compression level.
  level: 9

# GIF to video transcoding settings.
gif2video:
  enabled: false
