logging:
  console:
    enabled: false

  file:
    level: warn

cluster:
  enabled: true

metrics:
  statsd:
    spawn: false
  profile:
    heap:
      enabled: false

fork:
  enabled: true

cache:
  expire:
    default: 86400
